### ISSUE TITLE
出现null是因为什么?

### ISSUE THREAD

**Issue by shaoting0730** [Sky24n/fluintl#4]
![image](https://user-images.githubusercontent.com/14305431/59142971-90751e00-89f8-11e9-8fb6-ffe013bd823f.png)

**Comment by Sky24n** [comment]
应该是CustomLocalizations还没有初始化。

**Comment by shaoting0730** [comment]
我试了.如果只有一个界面可以取到值,如果是有tabbar的话就不行了

**Comment by Sky24n** [comment]
我的[flutter_wanandroid](https://github.com/Sky24n/flutter_wanandroid)项目里同样使用了tabbar，没有任何问题。
