### ISSUE TITLE
按照demo 编写遇到null 的错误。

### ISSUE THREAD

**Issue by uddsoft** [Sky24n/fluintl#7]
我的代码：
new Container(
                    padding: EdgeInsets.all(12.0),
                    child: new Text(
                      IntlUtil.getString(context, Ids.jump_count,
                          params: ['$_count']),
                      style: new TextStyle(fontSize: 14.0, color: Colors.white),
                    ),
                    decoration: new BoxDecoration(
                        color: Color(0x66000000),
                        borderRadius: BorderRadius.all(Radius.circular(4.0)),
                        border: new Border.all(
                            width: 0.33, color: Colours.divider))),
              ),
            )
I/flutter (23452): The following NoSuchMethodError was thrown building SplashPage(dirty, dependencies:
I/flutter (23452): [_LocalizationsScope-[GlobalKey#68099]], state: SplashPageState#c4229):
I/flutter (23452): The method 'getString' was called on null.
I/flutter (23452): Receiver: null
I/flutter (23452): Tried calling: getString("jump_count", countryCode: null, languageCode: null, params:
I/flutter (23452): Instance(length:1) of '_GrowableList')
I/flutter (23452): When the exception was thrown, this was the stack:
I/flutter (23452): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)

**Comment by Sky24n** [comment]
代码发全点！
或者你参考这个项目[flutter_wanandroid ](https://github.com/Sky24n/flutter_wanandroid)

**Comment by uddsoft** [comment]
谢谢，问题已解决。是使用IntlUtil.getString(context, Ids.jump_count,params: ['$_count'])没有进行初始化。
